---
- name: ansible-vault test playbook
  hosts: "nios"
  connection: local
  gather_facts: false

  vars:
    group_tag: "myapp2"
    debug: true
    policy: false

    # Options:
    # - none
    # - destination-port
    # - source-port
    combine: "{{ combine | default('none') }}"

    infoblox_host: "{{ inventory_hostname }}"
    infoblox_username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
    infoblox_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
    infoblox_wapi_version: v2.12.3

    subnet_classes:
      - cidr: "10.0.0.0/8"
        zone: "sddc-external"
        type: "external"
      - cidr: "172.16.0.0/12"
        zone: "sddc-external"
        type: "external"
      - cidr: "10.220.0.0/16"
        zone: "sddc-external"
        type: "internal"
      - cidr: "10.221.0.0/16"
        zone: "sddc-internal"
        type: "internal"
      - cidr: "10.229.0.0/16"
        zone: "sddc-internal"
        type: "internal"
      - cidr: "10.205.0.0/16"
        zone: "private"
        type: "azure"
      - cidr: "10.226.0.0/16"
        zone: "private"
        type: "azure"
      - cidr: "10.227.0.0/16"
        zone: "private"
        type: "azure"
      - cidr: "10.53.80.0/20"
        zone: "sddc-oob"
        type: "external"
      - cidr: "192.168.0.0/16"
        zone: "sddc-internal"
        type: "internal"

  tasks:
    - name: Resolve host IPs to Infoblox networks
      ansible.builtin.include_tasks: includes/resolve-firewall-row.yml
      loop: "{{ firewall_rules }}"
      loop_control:
        loop_var: rule
        label: "row {{ rule.row }}"

    - name: Init combined firewall rule variables
      ansible.builtin.set_fact:
        combined_rules: {}
        combined_firewall_rules: []

    - name: Build combined firewall rules
      ansible.builtin.set_fact:
        combined_rules: >-
          {{
            combined_rules | default({}) |
            combine({
              rule_key: existing_rule | combine({
                'applications': existing_rule.applications + [item.application | default(None)],
                'service_destination_ports': existing_rule.service_destination_ports + [item.service_destination_port | string],
                'rows': existing_rule.rows + [item.row],

                'sources': existing_rule.sources + [{
                  'address': item.source_address,
                  'name': item.source_name | default(None),
                  'ci': item.source_ci | default(None)
                }],

                'destinations': existing_rule.destinations + [{
                  'address': item.destination_address,
                  'name': item.destination_name | default(None),
                  'ci': item.destination_ci | default(None)
                }]
              })
            }, recursive=true)
          }}
      loop: "{{ firewall_rules_resolved }}"
      loop_control:
        label: "row {{ item.row }}"
      vars:
        rule_key: >-
          {% if combine == 'destination-port' %}
          {{
            [
              item.description,
              item.source_address,
              item.source_name | default(''),
              item.source_ci | default(''),
              item.source_zone,
              item.destination_zone,
              item.service_protocol | lower,
              item.group_id | default(''),
              item.action | lower,
              item.device_group
            ] | join('|')
          }}
          {% elif combine == 'source-port' %}
          {{
            [
              item.description,
              item.destination_address,
              item.destination_name | default(''),
              item.destination_ci | default(''),
              item.source_zone,
              item.destination_zone,
              item.service_protocol | lower,
              item.group_id | default(''),
              item.action | lower,
              item.device_group
            ] | join('|')
          }}
          {% else %}
          {{
            [
              item.description,
              item.source_address,
              item.source_name | default(''),
              item.source_ci | default(''),
              item.destination_address,
              item.destination_name | default(''),
              item.destination_ci | default(''),
              item.source_zone,
              item.destination_zone,
              item.service_protocol | lower,
              item.group_id | default(''),
              item.action | lower,
              item.device_group
            ] | join('|')
          }}
          {% endif %}

        existing_rule: >-
          {{
            combined_rules[rule_key] | default({
              'description': item.description,
              'source_zone': item.source_zone,
              'destination_zone': item.destination_zone,
              'service_protocol': item.service_protocol | lower,
              'group_id': item.group_id | default(None),
              'action': item.action | lower,
              'device_group': item.device_group,
              'applications': [],
              'service_destination_ports': [],
              'rows': [],
              'sources': [],
              'destinations': []
            })
          }}

    - name: Normalize combined firewall rules
      ansible.builtin.set_fact:
        combined_firewall_rules: "{{ combined_firewall_rules + [normalized_rule] }}"
      loop: "{{ combined_rules.values() | list }}"
      loop_control:
        label: "rows {{ item.rows }}"
      vars:
        normalized_rule: >-
          {{
            item | combine({
              'applications':
                item.applications
                | reject('equalto', none)
                | unique
                | sort,

              'service_destination_ports':
                item.service_destination_ports
                | reject('equalto', none)
                | unique
                | sort,

              'rows':
                item.rows
                | unique
                | sort,

              'sources':
                item.sources
                | rejectattr('address', 'equalto', none)
                | unique
                | list,

              'destinations':
                item.destinations
                | rejectattr('address', 'equalto', none)
                | unique
                | list
            })
          }}

    - name: Show combined firewall rules
      ansible.builtin.debug:
        var: combined_firewall_rules

    - name: Set stat combined_firewall_rules
      ansible.builtin.set_stats:
        data:
          combined_firewall_rules: "{{ combined_firewall_rules }}"

#    - name: Process firewall rules from JSON input
#      ansible.builtin.include_tasks: includes/process-firewall-rule.yml
#      loop: "{{ combined_firewall_rules }}"
#      loop_control:
#        loop_var: rule
#        label: "rows {{ rule.rows }} - {{ rule.description }}"
#      vars:
#        row: "{{ rule.rows }}"
#        description: "{{ rule.description }}"
#        source_zone: "{{ rule.source_zone }}"
#        destination_zone: "{{ rule.destination_zone }}"
#        group_id: "{{ rule.group_id }}"
#        service_protocol: "{{ rule.service_protocol | lower }}"
#        service_destination_port: "{{ rule.service_destination_ports }}"
#        action: "{{ rule.action | lower }}"
#        device_group: "{{ rule.device_group }}"
#        applications: "{{ rule.applications }}"
#        sources: "{{ rule.sources }}"
#        destinations: "{{ rule.destinations }}"