---
- name: Process firewall rule
  hosts: "panorama"
  connection: local
  gather_facts: false

  vars:
    perform_commit: false # set to false if you do not want the playbook to perform actual Panorama commits
    debug: false # set to true to show extra debug information
    explicit_rule_placement: true # set to true to attempt placing new rules in explicit order (requires lookup_tags to be true) - EXPERIMENTAL
    lookup_tags: true

    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: Process each combined firewall rule
      ansible.builtin.include_tasks: includes/process-firewall-rule.yml
      loop: "{{ combined_firewall_rules }}"
      loop_control:
        loop_var: rule
        label: "{{ rule.description }}"

    - name: Set stat processed_combined_firewall_rules
      ansible.builtin.set_stats:
        data:
          processed_combined_firewall_rules: "{{ processed_combined_firewall_rules }}"
