---
- name: Process firewall rule
  hosts: "panorama"
  connection: local
  gather_facts: false

  vars:
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
  # Source Address function
    - name: Get address objects from Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        state: gathered
        gathered_filter: "*"
      register: gathered_address_objects

    - name: Build requested source objects
      ansible.builtin.set_fact:
        requested_sources: >-
          {{
            combined_firewall_rules
            | map(attribute='sources')
            | flatten
            | unique(attribute='address')
          }}

    - name: Build list of existing Panorama address object values
      ansible.builtin.set_fact:
        existing_address_values: >-
          {{
            gathered_address_objects.gathered
            | map(attribute='value')
            | list
          }}

    - name: Determine missing source objects
      ansible.builtin.set_fact:
        missing_sources: >-
          {{
            requested_sources
            | rejectattr('address', 'in', existing_address_values)
            | list
          }}

    - name: Create missing address objects
      ansible.builtin.include_tasks: includes/create-address-object.yml
      loop: "{{ missing_sources }}"
      loop_control:
        loop_var: source

    - name: Build address value to object name map
      ansible.builtin.set_fact:
        address_object_map: >-
          {{
            address_object_map | default({}) |
            combine({
              item.value: item.name
            })
          }}
      loop: "{{ gathered_address_objects.gathered }}"

    - name: Build final combined firewall rules with source_addresses
      ansible.builtin.set_fact:
        combined_firewall_rules_resolved_source: >-
          {{
            combined_firewall_rules_resolved_source | default([]) +
            [
              item | combine({
                'source_addresses':
                  item.sources
                  | map(attribute='address')
                  | map('extract', address_object_map)
                  | list
              })
            ]
          }}
      loop: "{{ combined_firewall_rules }}"

    - name: Overwrite combined_firewall_rules with resolved version
      ansible.builtin.set_fact:
        combined_firewall_rules: "{{ combined_firewall_rules_resolved_source }}"

# Destination address function
    - name: Get address objects from Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        state: gathered
        gathered_filter: "*"
      register: gathered_address_objects

    - name: Build requested destination objects
      ansible.builtin.set_fact:
        requested_destinations: >-
          {{
            combined_firewall_rules_resolved_source
            | map(attribute='destinations')
            | flatten
            | unique(attribute='address')
          }}

    - name: Build list of existing Panorama address object values
      ansible.builtin.set_fact:
        existing_address_values: >-
          {{
            gathered_address_objects.gathered
            | map(attribute='value')
            | list
          }}

    - name: Determine missing destination objects
      ansible.builtin.set_fact:
        missing_destinations: >-
          {{
            requested_destinations
            | rejectattr('address', 'in', existing_address_values)
            | list
          }}

    - name: Create missing address objects
      ansible.builtin.include_tasks: includes/create-address-object.yml
      loop: "{{ missing_destinations }}"
      loop_control:
        loop_var: destination

    - name: Build address value to object name map
      ansible.builtin.set_fact:
        address_object_map: >-
          {{
            address_object_map | default({}) |
            combine({
              item.value: item.name
            })
          }}
      loop: "{{ gathered_address_objects.gathered }}"

    - name: Build final combined firewall rules with destination_addresses
      ansible.builtin.set_fact:
        combined_firewall_rules_resolved_destination: >-
          {{
            combined_firewall_rules_resolved_destination | default([]) +
            [
              item | combine({
                'destination_addresses':
                  item.destinations
                  | map(attribute='address')
                  | map('extract', address_object_map)
                  | list
              })
            ]
          }}
      loop: "{{ combined_firewall_rules_resolved_source }}"

    - name: Overwrite combined_firewall_rules with resolved version
      ansible.builtin.set_fact:
        combined_firewall_rules: "{{ combined_firewall_rules_resolved_destination }}"

# Service_object functions
    - name: Normalise input values for service_ports
      ansible.builtin.set_fact:
        normalised_service_destination_ports: "{{ combined_firewall_rules_resolved_destination.service_destination_ports | from_yaml }}"

    - name: Get service objects from Panorama
      paloaltonetworks.panos.panos_service_object:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: gathered_service_objects

    - name: Determine existing ports - Build list of all ports per defined protocol
      ansible.builtin.set_fact:
        existing_ports: >-
          {{
            gathered_service_objects.gathered
            | selectattr('protocol', 'equalto', service_protocol)
            | map(attribute='destination_port')
            | list
          }}

    - name: NEW Determine missing ports - compare service_destination_port to existing_ports
      ansible.builtin.set_fact:
        missing_ports: >-
          {{
            normalised_service_destination_ports | map('string') | difference(existing_ports)
          }}

#    - name: NEW Create missing service objects - loop through missing_ports we might have
#      ansible.builtin.include_tasks: includes/create-service-object.yml
#      loop: "{{ missing_ports }}"
#      loop_control:
#        loop_var: port
