---
- name: Process firewall rule
  hosts: "panorama"
  connection: local
  gather_facts: false

  vars:
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: Process each combined firewall rule
      ansible.builtin.include_tasks: includes/process-firewall-rule.yml
      loop: "{{ combined_firewall_rules }}"
      loop_control:
        loop_var: rule
        label: "{{ rule.description }}"
