---
- name: ansible-vault test playbook
  hosts: "panorama"
  connection: local
  gather_facts: false
  vars_files:
   - vault/vault-fwrules.yml

  vars:
    source_address: "192.168.0.16/28"
    destination_address: "10.221.7.1"
    service_protocol: "tcp"
    service_destination_port: '8082'
    infoblox_host: infoblox.zero-days.nl
    infoblox_wapi_version: v2.12.3
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: "{{ panorama_username }}"
      password: "{{ panorama_password }}"
    
    subnet_classes:
    - cidr: "10.0.0.0/8"
      zone: "sddc-external"
      type: "external"
    - cidr: "172.16.0.0/12"
      zone: "sddc-external"
      type: "external"
    - cidr: "10.220.0.0/16"
      zone: "sddc-external"
      type: "internal"
    - cidr: "10.221.0.0/16"
      zone: "sddc-internal"
      type: "internal"
    - cidr: "10.229.0.0/16"
      zone: "sddc-internal"
      type: "internal"
    - cidr: "10.205.0.0/16"
      zone: "private"
      type: "azure"
    - cidr: "10.226.0.0/16"
      zone: "private"
      type: "azure"
    - cidr: "10.227.0.0/16"
      zone: "private"
      type: "azure"
    - cidr: "10.53.80.0/20"
      zone: "sddc-oob"
      type: "external"
    - cidr: "192.168.0.0/16"
      zone: "any"
      type: "internal"

  tasks:
    - name: Show source input value
      ansible.builtin.debug:
        var: source_address

    - name: Show destination input value
      ansible.builtin.debug:
        var: destination_address

    - name: Determine if source and destination IPs are host or network
      ansible.builtin.set_fact:
        source_is_host: "{{ '/' not in source_address or source_address.endswith('/32') }}"
        source_is_network: "{{ '/' in source_address and not source_address.endswith('/32') }}"
        destination_is_host: "{{ '/' not in destination_address or destination_address.endswith('/32') }}"
        destination_is_network: "{{ '/' in destination_address and not destination_address.endswith('/32') }}" 

    - name: Find network for host source IP
      ansible.builtin.uri:
        url: "https://{{ infoblox_host }}/wapi/{{ infoblox_wapi_version }}/network?network_view=default&contains_address={{ source_address }}&_return_fields=network"
        method: GET
        user: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        force_basic_auth: true
        validate_certs: false
        return_content: true
      register: ib_network_lookup_src
      when: source_is_host

    - name: Show source value
      ansible.builtin.debug:
        var: ib_network_lookup_src.json[0].network

    - name: Set source_address to Infoblox result if exists
      ansible.builtin.set_fact:
        source_address: >-
          {{
            ib_network_lookup_src.json[0].network
            if ((ib_network_lookup_src.json | default([]) | length) > 0)
            else source_address
          }}

    - name: Set source_zone [1/2] - Set default source_zone to external
      ansible.builtin.set_fact:
        source_zone: "sddc-external"

    - name: Set source_zone [2/2] - Match source_zone from subnet list and overwrite standard source_zone
      ansible.builtin.set_fact:
        source_zone: "{{ item.zone }}"
        network_source_type: "{{ item.type }}"
      loop: "{{ subnet_classes }}"
      when: item.cidr | ansible.utils.network_in_network(source_address)

    - name: Find network for host destination IP
      ansible.builtin.uri:
        url: "https://{{ infoblox_host }}/wapi/{{ infoblox_wapi_version }}/network?network_view=default&contains_address={{ destination_address }}&_return_fields=network"
        method: GET
        user: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        force_basic_auth: true
        validate_certs: false
        return_content: true
      register: ib_network_lookup_dst
      when: destination_is_host

    - name: Show destination value
      ansible.builtin.debug:
        var: ib_network_lookup_dst.json[0].network

    - name: Set destination_address to Infoblox result if exists
      ansible.builtin.set_fact:
        destination_address: >-
          {{
            ib_network_lookup_dst.json[0].network
            if ((ib_network_lookup_dst.json | default([]) | length) > 0)
            else destination_address
          }}

    - name: Set destination_zone [1/2] - Set default destination_zone to external
      ansible.builtin.set_fact:
        destination_zone: "sddc-external"

    - name: Set destination_zone [2/2] - Match destination_zone from subnet list and overwrite standard destination_zone
      ansible.builtin.set_fact:
        destination_zone: "{{ item.zone }}"
        network_destination_type: "{{ item.type }}"
      loop: "{{ subnet_classes }}"
      when: item.cidr | ansible.utils.network_in_network(destination_address)

    - name: Determine device_group based on network type from subnet_classes
      ansible.builtin.set_fact:
        device_group: >-
          {%- set pair = [network_source_type, network_destination_type] | sort -%}
          {%- if pair == ['external', 'internal'] -%}
          ['sg_external']
          {%- elif pair == ['internal', 'internal'] -%}
          ['sg_internal']
          {%- elif pair == ['azure', 'internal'] -%}
          ['sg_external', 'sg_azure']
          {%- elif pair == ['azure', 'azure'] -%}
          ['sg_azure']
          {%- else -%}
          ['ERR-DG-NOT-FOUND']
          {%- endif -%}

    - name: Get address objects from Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: gathered_address_objects

    - name: Find firewall source object based on input variable [1/2] - Search for address object
      ansible.builtin.set_fact:
        source_address_object: >-
          {{ gathered_address_objects.gathered
            | selectattr('value', 'search', source_address)
            | map(attribute='name')
            | list }}

    - name: Find firewall source object based on input variable [2/2] - Fail if no address object was found
      ansible.builtin.fail:
        msg: >-
          No Palo Alto address_object found matching '{{ source_address }}'
      when: source_address_object | length == 0

    - name: Find firewall destination object based on input variable [1/2] - Search for address object
      ansible.builtin.set_fact:
        destination_address_object: >-
          {{ gathered_address_objects.gathered
            | selectattr('value', 'search', destination_address)
            | map(attribute='name')
            | list }}

    - name: Find firewall destination object based on input variable [2/2] - Fail if no address object was found
      ansible.builtin.fail:
        msg: >-
          No Palo Alto address_object found matching '{{ destination_address }}'
      when: destination_address_object | length == 0

    - name: Show source address object
      ansible.builtin.debug:
        var: source_address_object

    - name: Show destination address object
      ansible.builtin.debug:
        var: destination_address_object

    - name: Get service objects from Panorama
      paloaltonetworks.panos.panos_service_object:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: gathered_service_objects

    - name: Find matching service object names
      ansible.builtin.set_fact:
        service_object: >-
          {{
            gathered_service_objects.gathered
            | selectattr('protocol', 'equalto', service_protocol)
            | selectattr('destination_port', 'equalto', service_destination_port | string)
            | map(attribute='name')
            | list
          }}

    - name: Show service object
      ansible.builtin.debug:
        var: service_object

    - name: Include create service tasks on terraform host
      ansible.builtin.include_tasks: includes/create-service-object.yml
      when: service_object | length == 0
      vars:
        terraform_root: "/home/sstigter/panorama"
        services_file: "/home/sstigter/panorama/services.yaml"
