---
- name: ansible-vault test playbook
  hosts: all
  vars_files:
   - vault/vault-fwrules.yml

  tasks:
      - name: show vault encrypted variables
        debug: 
          msg: "{{infoblox_username}}"
