---
- name: ansible-vault test playbook
  hosts: "panorama"
  connection: local
  gather_facts: false
  vars_files:
   - vault/vault-fwrules.yml

  vars:
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: "{{ panorama_username }}"
      password: "{{ panorama_password }}"

  tasks:
    - name: Sample values
      ansible.builtin.set_fact:
        source_address: "192.168.0.16/28"
        destination_address: "10.221.7.1"

    - name: Determine if source and destination IPs are host or network
      ansible.builtin.set_fact:
        source_is_host: "{{ '/' not in source_address or source_address.endswith('/32') }}"
        source_is_network: "{{ '/' in source_address and not source_address.endswith('/32') }}"
        destination_is_host: "{{ '/' not in destination_address or destination_address.endswith('/32') }}"
        destination_is_network: "{{ '/' in destination_address and not destination_address.endswith('/32') }}" 

    - name: Find containing network for source IP
      ansible.builtin.uri:
        url: "https://infoblox.zero-days.nl/wapi/v2.12.3/network?network_view=default&contains_address={{ source_address }}&_return_fields=network"
        method: GET
        user: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        force_basic_auth: true
        validate_certs: false
        return_content: true
      register: ib_network_lookup_src
      when: source_is_host

    - name: Show source value
      ansible.builtin.debug:
        var: ib_network_lookup_src.json[0].network

    - name: Set source_address to Infoblox result if exists
      ansible.builtin.set_fact:
        source_address: >-
          {{
            (ib_network_lookup_src.json | default([])) | length > 0
            | ternary(
                ib_network_lookup_src.json[0].network,
                source_address
              )
          }}

    - name: Find containing network for destination IP
      ansible.builtin.uri:
        url: "https://infoblox.zero-days.nl/wapi/v2.12.3/network?network_view=default&contains_address={{ destination_address }}&_return_fields=network"
        method: GET
        user: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        force_basic_auth: true
        validate_certs: false
        return_content: true
      register: ib_network_lookup_dst
      when: destination_is_host

    - name: Show destination value
      ansible.builtin.debug:
        var: ib_network_lookup_dst.json[0].network

    - name: Set destination_address to Infoblox result if exists
      ansible.builtin.set_fact:
        destination_address: >-
          {{
            (ib_network_lookup_dst.json | default([])) | length > 0
            | ternary(
                ib_network_lookup_dst.json[0].network,
                destination_address
              )
          }}

    - name: Get address objects from Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: gathered_address_objects

    - name: Find firewall source object based on input variable [1/2] - Search for address object
      ansible.builtin.set_fact:
        source_address_object: >-
          {{ gathered_address_objects.gathered
            | selectattr('value', 'search', source_address)
            | map(attribute='name')
            | list }}

    - name: Find firewall source object based on input variable [2/2] - Fail if no address object was found
      ansible.builtin.fail:
        msg: >-
          No Palo Alto address_object found matching '{{ source_address }}'
      when: source_address_object | length == 0