---
- name: Firewall serial number list to run policy-checker against
  ansible.builtin.set_fact:
    firewall_list:
      SG-Internal: "013201003821"
      SG-External: "013201025327"
      SDDC Azure: "00795700713496"

- name: Firewall ip number list to run policy-checker against
  ansible.builtin.set_fact:
    firewall_list_ip:
      SG-Internal: "192.168.7.230"
      SG-External: "192.168.7.230"
      SDDC Azure: "192.168.7.230"

- name: Protocol list
  ansible.builtin.set_fact:
    protocol_list:
      icmp: "1"
      tcp: "6"
      udp: "17"

- name: Convert source EPG subnet to gateway address for rule validation
  ansible.builtin.set_fact:
    pol_source_address: "{{ rule.source_address | ansible.utils.ipaddr('net') | ansible.utils.ipaddr('-2') | ansible.utils.ipaddr('address') }}"
  when:
    - rule.network_source_type == "internal"

- name: Convert destination EPG subnet to gateway address for rule validation
  ansible.builtin.set_fact:
    pol_destination_address: "{{ rule.destination_address | ansible.utils.ipaddr('net') | ansible.utils.ipaddr('-2') | ansible.utils.ipaddr('address') }}"
  when:
    - rule.network_destination_type == "internal"

- name: Run panos match to check rules directly on firewall specified by device_group serial lookup
  paloaltonetworks.panos.panos_match_rule:
    provider:
      ip_address: "{{ firewall_list_ip[rule.device_group[0]] }}"
      username: "{{ panorama_username }}"
      password: "{{ panorama_password }}"
      #serial_number: "{{ firewall_list[rule.device_group[0]] }}"
    source_ip: "{{ pol_source_address }}"
    destination_ip: "{{ rule.destination_address }}"
    destination_port: "{{ rule.service_destination_port[0] }}"
    protocol: "{{ protocol_list[rule.service_protocol | lower] }}"
  when:
    - rule.network_source_type == "internal"

- name: Show matched rule
  ansible.builtin.debug:
    msg: >-
      matched rule: {{ result.rule | default('NO MATCH') }}
