---
- name: Normalise vaules
  # use better block
  ansible.builtin.set_fact:
    address: "{{ source.address | default(destination.address) }}"
    obj_name: >-
      {{
        source.name
        | default(destination.name, true)
        | default('', true)
      }}
    ci: >-
      {{
        source.ci
        | default(destination.ci, true)
        | default('', true)
      }}

- name: Determine if address is host or network
  ansible.builtin.set_fact:
    address_is_host: "{{ '/' not in address or address.endswith('/32') }}"
    address_is_network: "{{ '/' in address and not address.endswith('/32') }}"

- name: Set source host address object name
  ansible.builtin.set_fact:
    address_object_name: "ip_{{ address | replace('/', '_') }}"
  when: address_is_host

- name: Set source network address object name
  ansible.builtin.set_fact:
    address_object_name: "net_{{ address | replace('/', '_') }}"
  when: address_is_network

- name: Set host address value
  ansible.builtin.set_fact:
    address_object_value: "{{ address }}"

- name: Create address object on Panorama
  paloaltonetworks.panos.panos_address_object:
    provider: "{{ provider }}"
    name: "{{ address_object_name }}"
    value: "{{ address_object_value }}"
    device_group: shared

- name: Get address objects from Panorama again after creating missing objects
  paloaltonetworks.panos.panos_address_object:
    provider: "{{ provider }}"
    state: gathered
    gathered_filter: "*"
  register: gathered_address_objects
