---
- name: Set security group_profile lookup list
  ansible.builtin.set_fact:
    security_group_profile_list:
      SG-Internal: "sddc-strict-internal"
      SG-External: "sddc-strict-edge-bp"
      SDDC Azure: "sddc-strict-internal"
      ss-internal: "sddc-strict-internal"
      ss-external: "sddc-strict-edge-bp"

- name: Select processed firewall rule for current device_group we are running
  ansible.builtin.set_fact:
    processed_rule: >-
      {{
        processed_combined_firewall_rules
        | selectattr('device_group', 'contains', device_group_name)
        | list
        | first
      }}

- name: Get all security rules from Panorama for the device_group
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    device_group: "{{ device_group_name }}"
    state: 'gathered'
    gathered_filter: '*'
  register: security_rules

- name: Find tag based on input variable
  when: lookup_tags
  block:

    - name: Make sure last_rule_name is empty
      # Not sure why the var keeps sticking between loops, empty it out just to be sure
      ansible.builtin.set_fact:
        last_rule_name: ""

    - name: Find tag based on input variable - Get our application name from the EPG name
      ansible.builtin.set_fact:
        tag_object_name: "{{ group_by_ci }}"

    - name: Find tag based on input variable - Get tag objects from Panorama
      paloaltonetworks.panos.panos_tag_object:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: gathered_tag_objects

    - name: Find tag based on input variable - Search for tag object {{ tag_object_name }}
      ansible.builtin.set_fact:
        tag_object: >-
          {{ gathered_tag_objects.gathered
            | selectattr('name', 'search', tag_object_name)
            | rejectattr('name', 'match', '^0')
            | map(attribute='name')
            | list }}

    - name: Attempt explicit rule placement
      when: explicit_rule_placement
      block:

        - name: Attempt explicit rule placement [1/2] - Filter rules get all the rules with a group_tag matching tag object
          ansible.builtin.set_fact:
            tag_filtered_rules: >-
              {{
                security_rules.gathered
                | rejectattr('group_tag', 'equalto', none)
                | selectattr('group_tag', 'equalto', (tag_object | first))
                | list
              }}
          when:
            - tag_object is defined
            - (tag_object | length) > 0

        - name: Attempt explicit rule placement [2/2] - Get the rule name for the last rule in tag_filtered_rules list
          ansible.builtin.set_fact:
            last_rule_name: "{{ (tag_filtered_rules | last).rule_name }}"
          when: (tag_filtered_rules | default([]) | length) > 0

- name: Create security rule (no explicit placement)
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    device_group: "{{ device_group_name }}"
    rule_name: "{{ processed_rule.description }}"
    description: "{{ processed_rule.description }}"
    tag_name: "{{ processed_rule.tags }}"
    group_tag: "{{ (tag_object | default(['sddc - automated']) | first | default('sddc - automated')) | string | trim }}"
    source_zone: "{{ processed_rule.az_source_zone if device_group_name == 'SDDC Azure' else processed_rule.source_zone }}"
    source_ip: "{{ processed_rule.source_addresses | flatten }}"
    destination_zone: "{{ processed_rule.az_destination_zone if device_group_name == 'SDDC Azure' else processed_rule.destination_zone }}"
    destination_ip: "{{ processed_rule.destination_addresses }}"
    service: "{{ processed_rule.services }}"
    action: "{{ processed_rule.action }}"
    group_profile: "{{ security_group_profile_list[device_group_name] }}"
    log_setting: "forward-to-panorama"
    disabled: "no"
    audit_comment: "AAP job ID: {{ awx_job_id | default('n/a') }} - AAP User: {{ awx_user_name | default('n/a') }} - ICD: {{ ticket_num | default('no-CR') }}"
  when: (last_rule_name | default('') | string | trim | length) == 0

- name: Create security rule (place after rule {{ last_rule_name }})
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    device_group: "{{ device_group_name }}"
    rule_name: "{{ processed_rule.description }}"
    description: "{{ processed_rule.description }}"
    tag_name: "{{ processed_rule.tags }}"
    group_tag: "{{ (tag_object | default(['sddc - automated']) | first | default('sddc - automated')) | string | trim }}"
    source_zone: "{{ processed_rule.az_source_zone if device_group_name == 'SDDC Azure' else processed_rule.source_zone }}"
    source_ip: "{{ processed_rule.source_addresses | flatten }}"
    destination_zone: "{{ processed_rule.az_destination_zone if device_group_name == 'SDDC Azure' else processed_rule.destination_zone }}"
    destination_ip: "{{ processed_rule.destination_addresses }}"
    service: "{{ processed_rule.services }}"
    action: "{{ processed_rule.action }}"
    group_profile: "{{ security_group_profile_list[device_group_name] }}"
    log_setting: "forward-to-panorama"
    disabled: "no"
    audit_comment: "AAP job ID: {{ awx_job_id | default('n/a') }} - AAP User: {{ awx_user_name | default('n/a') }} - ICD: {{ ticket_num | default('no-CR') }}"
    location: 'after'
    existing_rule: "{{ last_rule_name }}"
  when: (last_rule_name | default('') | string | trim | length) > 0

- name: Append created address object to security_rules_created
  ansible.builtin.set_fact:
    security_rules_created: "{{ security_rules_created + [processed_rule.description] }}"

- name: Set commit needed to true
  ansible.builtin.set_fact:
    commit: true
  when: perform_commit

- name: Set push needed to true
  ansible.builtin.set_fact:
    push: true
  when: perform_commit

- name: Commit changes by ansible user when commit is needed + CHECK PUSH!
  # Commit changes when commit flag has been set
  paloaltonetworks.panos.panos_commit_panorama:
    provider: "{{ provider }}"
    admins: ['{{ provider.username }}']
    description: "AAP job ID: {{ awx_job_id | default('n/a') }} - AAP User: {{ awx_user_name | default('n/a') }} - ICD: {{ ticket_num | default('no-CR') }}"
  when: commit | default(false)

- name: Push device group configs
  # Push changes to DG when push flag has been set
  paloaltonetworks.panos.panos_commit_push:
    provider: "{{ provider }}"
    admins: ['{{ provider.username }}']
    style: "device group"
    name: "{{ device_group_name }}"
    description: "Push from Ansible orchestrator"
  when: push | default(false)
