---
- name: Set service name
  ansible.builtin.set_fact:
    service_name: "{{ service_protocol | lower }}-{{ port }}"

- name: Create service object
  paloaltonetworks.panos.panos_service_object:
    provider: "{{ provider }}"
    name: "{{ service_name }}"
    protocol: "{{ service_protocol }}"
    destination_port: "{{ port }}"

- name: Rerun Get service objects from Panorama
  paloaltonetworks.panos.panos_service_object:
    provider: "{{ provider }}"
    state: 'gathered'
    gathered_filter: '*'
  register: gathered_service_objects

- name: Rerun Find matching service object names
  ansible.builtin.set_fact:
    service_object: >-
      {{
        gathered_service_objects.gathered
        | selectattr('protocol', 'equalto', service_protocol | lower)
        | selectattr('destination_port', 'equalto', port | string)
        | map(attribute='name')
        | list
      }}
