---
# Source Address function
- name: Get address objects from Panorama
  paloaltonetworks.panos.panos_address_object:
    provider: "{{ provider }}"
    state: gathered
    gathered_filter: "*"
  register: gathered_address_objects

- name: Build requested source objects list from input variables
  ansible.builtin.set_fact:
    requested_sources: >-
      {{
        rule.sources
        | unique(attribute='address')
        | list
      }}

- name: Build list of existing Panorama address object values from gathered objects
  ansible.builtin.set_fact:
    existing_address_values: >-
      {{
        gathered_address_objects.gathered
        | map(attribute='value')
        | list
      }}

- name: Determine missing source objects by comparing lists
  ansible.builtin.set_fact:
    missing_sources: >-
      {{
        requested_sources
        | rejectattr('address', 'in', existing_address_values)
        | list
      }}

- name: Create missing source address objects
  ansible.builtin.include_tasks: includes/create-address-object.yml
  loop: "{{ missing_sources }}"
  loop_control:
    loop_var: source
    label: "{{ source.name | default(source.address) }}"

- name: Initialise resolved source addresses list
  ansible.builtin.set_fact:
    resolved_source_addresses: []

- name: Find firewall object based on requested_sources addresses
  ansible.builtin.set_fact:
    resolved_source_addresses: >-
      {{
        resolved_source_addresses
        +
        [
          (
            gathered_address_objects.gathered
            | selectattr('value', 'equalto', item.address)
            | map(attribute='name')
            | list
            | first
          )
        ]
      }}
  loop: "{{ requested_sources }}"
  loop_control:
    label: "{{ item.address }}"

# Destination Address function
- name: Build requested destination objects list from input variables
  ansible.builtin.set_fact:
    requested_destinations: >-
      {{
        rule.destinations
        | unique(attribute='address')
        | list
      }}

- name: Build list of existing Panorama address object values from gathered objects - TODO determine if this is dupe
  ansible.builtin.set_fact:
    existing_address_values: >-
      {{
        gathered_address_objects.gathered
        | map(attribute='value')
        | list
      }}

- name: Determine missing destination objects by comparing lists
  ansible.builtin.set_fact:
    missing_destinations: >-
      {{
        requested_destinations
        | rejectattr('address', 'in', existing_address_values)
        | list
      }}

- name: Create missing destination address objects
  ansible.builtin.include_tasks: includes/create-address-object.yml
  loop: "{{ missing_destinations }}"
  loop_control:
    loop_var: destination
    label: "{{ destination.name | default(destination.address) }}"

- name: Initialise resolved destination addresses list
  ansible.builtin.set_fact:
    resolved_destination_addresses: []

- name: Find firewall object based on requested_destinations addresses
  ansible.builtin.set_fact:
    resolved_destination_addresses: >-
      {{
        resolved_destination_addresses
        +
        [
          (
            gathered_address_objects.gathered
            | selectattr('value', 'equalto', item.address)
            | map(attribute='name')
            | list
            | first
          )
        ]
      }}
  loop: "{{ requested_destinations }}"
  loop_control:
    label: "{{ item.address }}"

# Service object functions
- name: Normalise input values for service ports
  ansible.builtin.set_fact:
    normalised_service_destination_ports: >-
      {{
        (
          rule.service_destination_ports
          | map('from_yaml')
          | flatten
        )
        if
          rule.service_destination_ports | length > 0
          and rule.service_destination_ports[0] is string
          and rule.service_destination_ports[0].startswith('[')
        else
          rule.service_destination_ports
      }}

- name: Split service destination ports by protocol
  ansible.builtin.set_fact:
    service_destination_ports_tcp: >-
      {{
        normalised_service_destination_ports
        | select('match', '^tcp-')
        | list
      }}
    service_destination_ports_udp: >-
      {{
        normalised_service_destination_ports
        | select('match', '^udp-')
        | list
      }}

- name: Strip protocol prefix after splitting
  ansible.builtin.set_fact:
    service_destination_ports_tcp_raw: >-
      {{
        service_destination_ports_tcp
        | map('regex_replace', '^tcp-', '')
        | list
      }}
    service_destination_ports_udp_raw: >-
      {{
        service_destination_ports_udp
        | map('regex_replace', '^udp-', '')
        | list
      }}

- name: Get service objects from Panorama
  paloaltonetworks.panos.panos_service_object:
    provider: "{{ provider }}"
    state: gathered
    gathered_filter: "*"
  register: gathered_service_objects

- name: Normalise input values for service protcol
  ansible.builtin.set_fact:
    normalised_service_protocol: "tcp"

- name: Determine existing ports - Build list of all ports per defined protocol
  ansible.builtin.set_fact:
    existing_ports: >-
      {{
        gathered_service_objects.gathered
        | selectattr('protocol', 'equalto', normalised_service_protocol)
        | map(attribute='destination_port')
        | map('string')
        | list
      }}

- name: Determine missing ports - compare service destination ports to existing ports
  ansible.builtin.set_fact:
    missing_ports: >-
      {{
        service_destination_ports_tcp_raw
        | map('string')
        | difference(existing_ports)
      }}

- name: Create missing service objects
  ansible.builtin.include_tasks: includes/create-service-object.yml
  loop: "{{ missing_ports }}"
  loop_control:
    loop_var: port
    label: "{{ normalised_service_protocol }}-{{ port }}"
  vars:
    service_protocol: "{{ normalised_service_protocol }}"

- name: Initialise resolved service object list
  ansible.builtin.set_fact:
    resolved_services: []

- name: Find service objects based on requested destination ports and protocol
  ansible.builtin.set_fact:
    resolved_services: >-
      {{
        resolved_services
        +
        (
          gathered_service_objects.gathered
          | selectattr('protocol', 'equalto', normalised_service_protocol)
          | selectattr('destination_port', 'equalto', item | string)
          | map(attribute='name')
          | list
        )
      }}
  loop: "{{ normalised_service_destination_ports }}"
  loop_control:
    label: "{{ normalised_service_protocol }}-{{ item }}"

# tag object functions
- name: Find tag based on input variable - Get tag objects from Panorama
  paloaltonetworks.panos.panos_tag_object:
    provider: "{{ provider }}"
    state: gathered
    gathered_filter: '*'
  register: gathered_tag_objects

- name: Build unique source CI list
  ansible.builtin.set_fact:
    source_ci_list: >-
      {{
        rule.sources
        | map(attribute='ci')
        | map('string')
        | unique
        | list
      }}

- name: Build unique destination CI list
  ansible.builtin.set_fact:
    destination_ci_list: >-
      {{
        rule.destinations
        | map(attribute='ci')
        | map('string')
        | unique
        | list
      }}

- name: Initialise resolved tags list - starting with predefined automated tag
  ansible.builtin.set_fact:
    resolved_tag: ["sddc - automated"]

- name: Append matching Panorama source tags by looping through source CI list
  ansible.builtin.set_fact:
    resolved_tag: >-
      {{
        resolved_tag
        +
        (
          gathered_tag_objects.gathered
          | selectattr('name', 'search', item)
          | rejectattr('name', 'match', '^0')
          | map(attribute='name')
          | list
        )
      }}
  loop: "{{ source_ci_list }}"
  loop_control:
    label: "{{ item }}"

- name: Append matching Panorama destination tags by looping through destination CI list
  ansible.builtin.set_fact:
    resolved_tag: >-
      {{
        resolved_tag
        +
        (
          gathered_tag_objects.gathered
          | selectattr('name', 'search', item)
          | rejectattr('name', 'match', '^0')
          | map(attribute='name')
          | list
        )
      }}
  loop: "{{ destination_ci_list }}"
  loop_control:
    label: "{{ item }}"

- name: Remove duplicate tags by unique-ing our list
  ansible.builtin.set_fact:
    resolved_tag: "{{ resolved_tag | unique | list }}"

- name: Add resolved values to processed firewall rule list
  ansible.builtin.set_fact:
    processed_combined_firewall_rules: >-
      {{
        processed_combined_firewall_rules | default([]) +
        [
          rule | combine({
            'source_addresses': resolved_source_addresses,
            'destination_addresses': resolved_destination_addresses,
            'services': resolved_services,
            'tags': resolved_tag
          })
        ]
      }}

- name: Create the security rule looping through the device_groups
  ansible.builtin.include_tasks: includes/create-security-rule.yml
  loop: "{{ rule.device_group }}"
  loop_control:
    loop_var: device_group_name
    label: "{{ device_group_name }}"
  when: create_rule
